#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

FONT="Hack Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)
RIGHT_BAR_ITEMS_SPACE=10 # Padding between items on the right side of the bar

##### Changing Defaults #####

# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

bar=(
  height=32
  color=$BAR_COLOR
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  blur_radius=30
  padding_right=10
  padding_left=10
  topmost=window
  # color=0x00000000
  # border_color=0x00000000
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:17.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Bold:14.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  label.shadow.drawing=on
  label.shadow.distance=2
  label.shadow.color=0xff000000
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on

)

sketchybar --default "${defaults[@]}"
##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# source $ITEMS_DIR/aerospace.sh
source $ITEMS_DIR/spaces.sh
source $ITEMS_DIR/front_app.sh

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

source $ITEMS_DIR/calendar.sh
source $ITEMS_DIR/battery.sh
source $ITEMS_DIR/cpu.sh
source $ITEMS_DIR/volume.sh
source $ITEMS_DIR/keyboard.sh
sketchybar --add alias "Axis Client" right \
           --set "Axis Client" click_script='open -a "Axis Client"'
sketchybar --add alias "Flow" right \
           --set Flow click_script="open -a Flow"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
sketchybar --add event aerospace_workspace_change
dynamic-island-sketchybar
