keybinding:
    commits:
        moveDownCommit: '<c-e>'
        moveUpCommit: '<c-u>'
git:
    overrideGpg: true
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme base16-256 -s
