keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - key: O
      builtin: checkout
    - key: C
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c "pr edit {{.PrNumber}}"
        '
    - key: b
      command: cd {{.RepoPath}} && gh pr view {{.PrNumber}} --json statusCheckRollup | command jq -rcj '.statusCheckRollup.[] | select(.context == "buildkite/mono") | .targetUrl' | xargs open
    - key: a
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

repoPaths:
  cyeragit/cyera: ~/checkouts/cyera
  cyeragit/cyera-flux: ~/checkouts/cyera-flux
